export enum TodosActionTypes {
  FETCH_TODOS = 'FETCH_TODOS',
  SET_TODOS = 'SET_TODOS',
  UPDATE_TODO = 'UPDATE_TODO',
  DELETE_TODO = 'DELETE_TODO',
  CREATE_TODO = 'CREATE_TODO',
  SET_TODO_FILTER = 'SET_TODO_FILTER',
  SET_SORT_OPTIONS = 'SET_SORT_OPTIONS',
}
